### ISSUE TITLE
Menjanje labela u sideBar-u preko MousePressEvent-a

### ISSUE THREAD

**Issue by milosavljevic** [MATF-RS15/rs15-22#3]
Neke stvari (polja metode, ili neki interfejs) moramo da stavimo na public u klasi mainwindow, kako bi bilo moguće menjati Sidebar kroz interakciju sa scenom. Šta da stavimo na public?

**Comment by petarvukmirovic** [comment]
Pokusaj da tu klasu koja ce reagovati proglasis prijateljem ili
jednostavnonkoristo signale inslotove. Na kakav si problem tacno naisao?

**Comment by milosavljevic** [comment]
Pa mogao bih to da sredim time sto bih koristio Friend funkcije, ali nisam siguran koliko je to elegantno resenje...

**Comment by petarvukmirovic** [comment]
Meni licno je jedna prijateljska klasa elegantnija nego 30 getera i setera
koje koristi samo ta jedna klasa (Java resenje). To moze da sugerise
korisnicima klase da je nesto namenjeno za spoljasnju upotrebu iako stvarno
nije. Odluci kako ti je lepse :)

**Comment by petarvukmirovic** [comment]
Naravno, pozdrav za autore Qta uz zelju da mi objasne zasto su stavili
EventHandler iako toliko potenciraju na signalima i slotovima
