### ISSUE TITLE
Pretvaranje iz o_id u std::string ili bilo koji drugi "normalan" objekat nije straight forward.

### ISSUE THREAD

**Issue by milosavljevic** [MATF-RS15/rs15-22#4]
ne postoji nacin da se normalno proveri vrednost null za roditelja.

**Comment by petarvukmirovic** [comment]
Zar nije to Subotic resio sa .value?

**Comment by petarvukmirovic** [comment]
Stavicemo polje hasParent u bazu nije ni bitno
